name: vibe_podcasts
description: "a podcast application created in flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.10.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  firebase_storage: ^11.7.5
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  just_audio: ^0.9.39
  just_audio_background: 0.0.1-beta.13
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  json_serializable: ^6.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true































